language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0

sudo: required

before_install:
  - gem install bundler -v 1.10.5

  # install mono & friends
  - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install -y mono-complete referenceassemblies-pcl

  # install dnvm & dnx
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade -y
